#!/usr/bin/env bash
# Bash script containing commands to automatically configure a Ubuntu machine
# Configure your Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently"

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
Redirect="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://overapi.com/;\n\t}\n"
sudo sed -i "53i $Redirect" /etc/nginx/sites-available/default

sudo service nginx restart
