#!/usr/bin/env bash
# Bash script containing commands to automatically configure a Ubuntu machine
# Configure your Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently"


