#!/usr/bin/env bash
# displays numbers from 1 to 100 in list format.
#   Displays "FizzBuzz" when the number is a multiple of both 3 and 5.
#   Displays "Fizz" when the number is a multiple of 3.
#   Displays "Buzz" when the number is a multiple of 5.
#   Otherwise, displays the number.

# loop through numbers from 1 to 100
for num in {1..100}
do
if (( num % 3 == 0 && num % 5 == 0 )) # check if number is a multiple of both 3 and 5
then
echo "FizzBuzz"
elif (( num % 3 == 0 )) # check if number is a multiple of 3
then
echo "Fizz"
elif (( num % 5 == 0 )) # check if number is a multiple of 5
then
echo "Buzz"
else # number is not a multiple of 3 or 5
echo "$num"
fi
done
