#!/usr/bin/env bash
# This displays the contents of the file `/etc/passwd`.
#   Only displays the username, user id, and user home directory path.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
