#!/usr/bin/env bash
# This displays the contents of the current directory in list format.
# and displays the part of the name after the first dash. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
