#!/usr/bin/env bash
# Bash script that configures the container to fit the above requirements

configure_nginx_user() {
    sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
}

configure_nginx_port() {
    sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
}

restart_nginx() {
    service nginx restart
}
